export const curreniesSymbols = {
    "AED": { "name": "UAE-Dirham", "symbol": " د.إ" },
    "AFN": { "name": "Afghanistan Afghani", "symbol": "؋" },
    "ALL": { "name": "Albania Lek", "symbol": "Lek" },
    "ANG": { "name": "Netherlands Antilles Guilder", "symbol": "ƒ" },
    "ARS": { "name": "Argentina Peso", "symbol": "$" },
    "AUD": { "name": "Australia Dollar", "symbol": "$" },
    "AWG": { "name": "Aruba Guilder", "symbol": "ƒ" },
    "AZN": { "name": "Azerbaijan Manat", "symbol": "₼" },
    "BAM": { "name": "Bosnia and Herzegovina Convertible Mark", "symbol": "KM" },
    "BBD": { "name": "Barbados Dollar", "symbol": "$" },
    "BDT": { "name": "Bangladesh Taka", "symbol": "৳" },
    "BGN": { "name": "Bulgaria Lev", "symbol": "лв" },
    "BHD": { "name": "Bahraini Dinar", "symbol": ".د.ب" },
    "BMD": { "name": "Bermuda Dollar", "symbol": "$" },
    "BND": { "name": "Brunei Darussalam Dollar", "symbol": "$" },
    "BOB": { "name": "Bolivia Bolíviano", "symbol": "$b" },
    "BRL": { "name": "Brazil Real", "symbol": "R$" },
    "BSD": { "name": "Bahamas Dollar", "symbol": "$" },
    "BTN": { "name": "Bhutan Ngultrum", "symbol": "Nu." },
    "BWP": { "name": "Botswana Pula", "symbol": "P" },
    "BYN": { "name": "Belarus Ruble", "symbol": "Br" },
    "BZD": { "name": "Belize Dollar", "symbol": "BZ$" },
    "CAD": { "name": "Canada Dollar", "symbol": "$" },
    "CDF": { "name": "Congo/Kinshasa Franc", "symbol": "FC" },
    "CHF": { "name": "Switzerland Franc", "symbol": "CHF" },
    "CLP": { "name": "Chile Peso", "symbol": "$" },
    "CNY": { "name": "China Yuan Renminbi", "symbol": "¥" },
    "COP": { "name": "Colombia Peso", "symbol": "$" },
    "CRC": { "name": "Costa Rica Colon", "symbol": "₡" },
    "CUP": { "name": "Cuba Peso", "symbol": "₱" },
    "CVE": { "name": "Cape Verde Escudo", "symbol": "$" },
    "CZK": { "name": "Czech Republic Koruna", "symbol": "Kč" },
    "DJF": { "name": "Djibouti Franc", "symbol": "Fdj" },
    "DKK": { "name": "Denmark Krone", "symbol": "kr" },
    "DOP": { "name": "Dominican Republic Peso", "symbol": "RD$" },
    "DZD": { "name": "Algerian Dinar", "symbol": "دج" },
    "EGP": { "name": "Egypt Pound", "symbol": "£" },
    "ERN": { "name": "Eritrea Nakfa", "symbol": "Nfk" },
    "ETB": { "name": "Ethiopia Birr", "symbol": "Br" },
    "EUR": { "name": "Euro Member Countries", "symbol": "€" },
    "FJD": { "name": "Fiji Dollar", "symbol": "$" },
    "FKP": { "name": "Falkland Islands (Malvinas) Pound", "symbol": "£" },
    "GBP": { "name": "United Kingdom Pound", "symbol": "£" },
    "GEL": { "name": "Georgia Lari", "symbol": "₾" },
    "GGP": { "name": "Guernsey Pound", "symbol": "£" },
    "GHS": { "name": "Ghana Cedi", "symbol": "¢" },
    "GIP": { "name": "Gibraltar Pound", "symbol": "£" },
    "GMD": { "name": "Gambia Dalasi", "symbol": "D" },
    "GNF": { "name": "Guinea Franc", "symbol": "FG" },
    "GTQ": { "name": "Guatemala Quetzal", "symbol": "Q" },
    "GYD": { "name": "Guyana Dollar", "symbol": "$" },
    "HKD": { "name": "Hong Kong Dollar", "symbol": "$" },
    "HNL": { "name": "Honduras Lempira", "symbol": "L" },
    "HRK": { "name": "Croatia Kuna", "symbol": "kn" },
    "HTG": { "name": "Haiti Gourde", "symbol": "G" },
    "HUF": { "name": "Hungary Forint", "symbol": "Ft" },
    "IDR": { "name": "Indonesia Rupiah", "symbol": "Rp" },
    "ILS": { "name": "Israel Shekel", "symbol": "₪" },
    "IMP": { "name": "Isle of Man Pound", "symbol": "£" },
    "INR": { "name": "India Rupee", "symbol": "₹" },
    "IQD": { "name": "Iraq Dinar", "symbol": "ع.د" },
    "IRR": { "name": "Iran Rial", "symbol": "﷼" },
    "ISK": { "name": "Iceland Krona", "symbol": "kr" },
    "JEP": { "name": "Jersey Pound", "symbol": "£" },
    "JMD": { "name": "Jamaica Dollar", "symbol": "J$" },
    "JOD": { "name": "Jordan Dinar", "symbol": "د.ا" },
    "JPY": { "name": "Japan Yen", "symbol": "¥" },
    "KES": { "name": "Kenya Shilling", "symbol": "KSh" },
    "KGS": { "name": "Kyrgyzstan Som", "symbol": "лв" },
    "KHR": { "name": "Cambodia Riel", "symbol": "៛" },
    "KID": { "name": "Kiribati Dollar", "symbol": "$" },
    "KMF": { "name": "Comoros Franc", "symbol": "CF" },
    "KRW": { "name": "Korea (South) Won", "symbol": "₩" },
    "KWD": { "name": "Kuwait Dinar", "symbol": "د.ك" },
    "KYD": { "name": "Cayman Islands Dollar", "symbol": "$" },
    "KZT": { "name": "Kazakhstan Tenge", "symbol": "лв" },
    "LAK": { "name": "Laos Kip", "symbol": "₭" },
    "LBP": { "name": "Lebanon Pound", "symbol": "£" },
    "LKR": { "name": "Sri Lanka Rupee", "symbol": "₨" },
    "LRD": { "name": "Liberia Dollar", "symbol": "$" },
    "LSL": { "name": "Lesotho Loti", "symbol": "L" },
    "LYD": { "name": "Libya Dinar", "symbol": "ل.د" },
    "MAD": { "name": "Morocco Dirham", "symbol": "د.م." },
    "MDL": { "name": "Moldova Leu", "symbol": "lei" },
    "MGA": { "name": "Madagascar Ariary", "symbol": "Ar" },
    "MKD": { "name": "Macedonia Denar", "symbol": "ден" },
    "MMK": { "name": "Myanmar Kyat", "symbol": "K" },
    "MNT": { "name": "Mongolia Tughrik", "symbol": "₮" },
    "MOP": { "name": "Macau Pataca", "symbol": "MOP$" },
    "MRU": { "name": "Mauritania Ouguiya", "symbol": "UM" },
    "MUR": { "name": "Mauritius Rupee", "symbol": "₨" },
    "MVR": { "name": "Maldives Rufiyaa", "symbol": "Rf" },
    "MWK": { "name": "Malawi Kwacha", "symbol": "MK" },
    "MXN": { "name": "Mexico Peso", "symbol": "$" },
    "MYR": { "name": "Malaysia Ringgit", "symbol": "RM" },
    "MZN": { "name": "Mozambique Metical", "symbol": "MT" },
    "NAD": { "name": "Namibia Dollar", "symbol": "$" },
    "NGN": { "name": "Nigeria Naira", "symbol": "₦" },
    "NIO": { "name": "Nicaragua Cordoba", "symbol": "C$" },
    "NOK": { "name": "Norway Krone", "symbol": "kr" },
    "NPR": { "name": "Nepal Rupee", "symbol": "₨" },
    "NZD": { "name": "New Zealand Dollar", "symbol": "$" },
    "OMR": { "name": "Oman Rial", "symbol": "﷼" },
    "PAB": { "name": "Panama Balboa", "symbol": "B/." },
    "PEN": { "name": "Peru Sol", "symbol": "S/." },
    "PGK": { "name": "Papua New Guinea Kina", "symbol": "K" },
    "PHP": { "name": "Philippines Peso", "symbol": "₱" },
    "PKR": { "name": "Pakistan Rupee", "symbol": "₨" },
    "PLN": { "name": "Poland Zloty", "symbol": "zł" },
    "PYG": { "name": "Paraguay Guarani", "symbol": "Gs" },
    "QAR": { "name": "Qatar Riyal", "symbol": "﷼" },
    "RON": { "name": "Romania Leu", "symbol": "lei" },
    "RSD": { "name": "Serbia Dinar", "symbol": "Дин." },
    "RUB": { "name": "Russia Ruble", "symbol": "₽" },
    "RWF": { "name": "Rwanda Franc", "symbol": "RF" },
    "SAR": { "name": "Saudi Arabia Riyal", "symbol": "﷼" },
    "SBD": { "name": "Solomon Islands Dollar", "symbol": "$" },
    "SCR": { "name": "Seychelles Rupee", "symbol": "₨" },
    "SDG": { "name": "Sudan Pound", "symbol": "£" },
    "SEK": { "name": "Sweden Krona", "symbol": "kr" },
    "SGD": { "name": "Singapore Dollar", "symbol": "$" },
    "SHP": { "name": "Saint Helena Pound", "symbol": "£" },
    "SLL": { "name": "Sierra Leone Leone", "symbol": "Le" },
    "SOS": { "name": "Somalia Shilling", "symbol": "S" },
    "SRD": { "name": "Suriname Dollar", "symbol": "$" },
    "SSP": { "name": "South Sudanese Pound", "symbol": "£" },
    "STN": { "name": "São Tomé and Príncipe Dobra", "symbol": "Db" },
    "SYP": { "name": "Syria Pound", "symbol": "£" },
    "SZL": { "name": "Swaziland Lilangeni", "symbol": "E" },
    "THB": { "name": "Thailand Baht", "symbol": "฿" },
    "TJS": { "name": "Tajikistan Somoni", "symbol": "ЅМ" },
    "TMT": { "name": "Turkmenistan Manat", "symbol": "T" },
    "TND": { "name": "Tunisia Dinar", "symbol": "د.ت" },
    "TOP": { "name": "Tonga Pa'anga", "symbol": "T$" },
    "TRY": { "name": "Turkey Lira", "symbol": "₺" },
    "TTD": { "name": "Trinidad and Tobago Dollar", "symbol": "TT$" },
    "TVD": { "name": "Tuvalu Dollar", "symbol": "$" },
    "TWD": { "name": "Taiwan New Dollar", "symbol": "NT$" },
    "TZS": { "name": "Tanzania Shilling", "symbol": "TSh" },
    "UAH": { "name": "Ukraine Hryvnia", "symbol": "₴" },
    "UGX": { "name": "Uganda Shilling", "symbol": "USh" },
    "USD": { "name": "United States Dollar", "symbol": "$" },
    "UYU": { "name": "Uruguay Peso", "symbol": "$U" },
    "UZS": { "name": "Uzbekistan Som", "symbol": "лв" },
    "VES": { "name": "Venezuela Bolívar", "symbol": "Bs" },
    "VND": { "name": "Viet Nam Dong", "symbol": "₫" },
    "VUV": { "name": "Vanuatu Vatu", "symbol": "VT" },
    "WST": { "name": "Samoa Tala", "symbol": "WS$" },
    "XAF": { "name": "Communauté Financière Africaine (BEAC) CFA Franc BEAC", "symbol": "FCFA" },
    "XCD": { "name": "East Caribbean Dollar", "symbol": "$" },
    "XDR": { "name": "International Monetary Fund (IMF) Special Drawing Rights", "symbol": "SDR" },
    "XOF": { "name": "Communauté Financière Africaine (BCEAO) Franc", "symbol": "CFA" },
    "XPF": { "name": "Comptoirs Français du Pacifique (CFP) Franc", "symbol": "CFPF" },
    "YER": { "name": "Yemen Rial", "symbol": "﷼" },
    "ZAR": { "name": "South Africa Rand", "symbol": "R" },
    "ZMW": { "name": "Zambia Kwacha", "symbol": "ZK" },
    "ZWL": { "name": "Zimbabwe Dollar", "symbol": "Z$" }
}

export const currencies = [
    { "AED": { "name": "UAE-Dirham", "symbol": " د.إ" } },
    { "AFN": { "name": "Afghanistan Afghani", "symbol": "؋" } },
    { "ALL": { "name": "Albania Lek", "symbol": "Lek" } },
    { "ANG": { "name": "Netherlands Antilles Guilder", "symbol": "ƒ" } },
    { "ARS": { "name": "Argentina Peso", "symbol": "$" } },
    { "AUD": { "name": "Australia Dollar", "symbol": "$" } },
    { "AWG": { "name": "Aruba Guilder", "symbol": "ƒ" } },
    { "AZN": { "name": "Azerbaijan Manat", "symbol": "₼" } },
    { "BAM": { "name": "Bosnia and Herzegovina Convertible Mark", "symbol": "KM" } },
    { "BBD": { "name": "Barbados Dollar", "symbol": "$" } },
    { "BDT": { "name": "Bangladesh Taka", "symbol": "৳" } },
    { "BGN": { "name": "Bulgaria Lev", "symbol": "лв" } },
    { "BHD": { "name": "Bahraini Dinar", "symbol": ".د.ب" } },
    { "BMD": { "name": "Bermuda Dollar", "symbol": "$" } },
    { "BND": { "name": "Brunei Darussalam Dollar", "symbol": "$" } },
    { "BOB": { "name": "Bolivia Bolíviano", "symbol": "$b" } },
    { "BRL": { "name": "Brazil Real", "symbol": "R$" } },
    { "BSD": { "name": "Bahamas Dollar", "symbol": "$" } },
    { "BTN": { "name": "Bhutan Ngultrum", "symbol": "Nu." } },
    { "BWP": { "name": "Botswana Pula", "symbol": "P" } },
    { "BYN": { "name": "Belarus Ruble", "symbol": "Br" } },
    { "BZD": { "name": "Belize Dollar", "symbol": "BZ$" } },
    { "CAD": { "name": "Canada Dollar", "symbol": "$" } },
    { "CDF": { "name": "Congo/Kinshasa Franc", "symbol": "FC" } },
    { "CHF": { "name": "Switzerland Franc", "symbol": "CHF" } },
    { "CLP": { "name": "Chile Peso", "symbol": "$" } },
    { "CNY": { "name": "China Yuan Renminbi", "symbol": "¥" } },
    { "COP": { "name": "Colombia Peso", "symbol": "$" } },
    { "CRC": { "name": "Costa Rica Colon", "symbol": "₡" } },
    { "CUP": { "name": "Cuba Peso", "symbol": "₱" } },
    { "CVE": { "name": "Cape Verde Escudo", "symbol": "$" } },
    { "CZK": { "name": "Czech Republic Koruna", "symbol": "Kč" } },
    { "DJF": { "name": "Djibouti Franc", "symbol": "Fdj" } },
    { "DKK": { "name": "Denmark Krone", "symbol": "kr" } },
    { "DOP": { "name": "Dominican Republic Peso", "symbol": "RD$" } },
    { "DZD": { "name": "Algerian Dinar", "symbol": "دج" } },
    { "EGP": { "name": "Egypt Pound", "symbol": "£" } },
    { "ERN": { "name": "Eritrea Nakfa", "symbol": "Nfk" } },
    { "ETB": { "name": "Ethiopia Birr", "symbol": "Br" } },
    { "EUR": { "name": "Euro Member Countries", "symbol": "€" } },
    { "FJD": { "name": "Fiji Dollar", "symbol": "$" } },
    { "FKP": { "name": "Falkland Islands (Malvinas) Pound", "symbol": "£" } },
    { "GBP": { "name": "United Kingdom Pound", "symbol": "£" } },
    { "GEL": { "name": "Georgia Lari", "symbol": "₾" } },
    { "GGP": { "name": "Guernsey Pound", "symbol": "£" } },
    { "GHS": { "name": "Ghana Cedi", "symbol": "¢" } },
    { "GIP": { "name": "Gibraltar Pound", "symbol": "£" } },
    { "GMD": { "name": "Gambia Dalasi", "symbol": "D" } },
    { "GNF": { "name": "Guinea Franc", "symbol": "FG" } },
    { "GTQ": { "name": "Guatemala Quetzal", "symbol": "Q" } },
    { "GYD": { "name": "Guyana Dollar", "symbol": "$" } },
    { "HKD": { "name": "Hong Kong Dollar", "symbol": "$" } },
    { "HNL": { "name": "Honduras Lempira", "symbol": "L" } },
    { "HRK": { "name": "Croatia Kuna", "symbol": "kn" } },
    { "HTG": { "name": "Haiti Gourde", "symbol": "G" } },
    { "HUF": { "name": "Hungary Forint", "symbol": "Ft" } },
    { "IDR": { "name": "Indonesia Rupiah", "symbol": "Rp" } },
    { "ILS": { "name": "Israel Shekel", "symbol": "₪" } },
    { "IMP": { "name": "Isle of Man Pound", "symbol": "£" } },
    { "INR": { "name": "India Rupee", "symbol": "₹" } },
    { "IQD": { "name": "Iraq Dinar", "symbol": "ع.د" } },
    { "IRR": { "name": "Iran Rial", "symbol": "﷼" } },
    { "ISK": { "name": "Iceland Krona", "symbol": "kr" } },
    { "JEP": { "name": "Jersey Pound", "symbol": "£" } },
    { "JMD": { "name": "Jamaica Dollar", "symbol": "J$" } },
    { "JOD": { "name": "Jordan Dinar", "symbol": "د.ا" } },
    { "JPY": { "name": "Japan Yen", "symbol": "¥" } },
    { "KES": { "name": "Kenya Shilling", "symbol": "KSh" } },
    { "KGS": { "name": "Kyrgyzstan Som", "symbol": "лв" } },
    { "KHR": { "name": "Cambodia Riel", "symbol": "៛" } },
    { "KID": { "name": "Kiribati Dollar", "symbol": "$" } },
    { "KMF": { "name": "Comoros Franc", "symbol": "CF" } },
    { "KRW": { "name": "Korea (South) Won", "symbol": "₩" } },
    { "KWD": { "name": "Kuwait Dinar", "symbol": "د.ك" } },
    { "KYD": { "name": "Cayman Islands Dollar", "symbol": "$" } },
    { "KZT": { "name": "Kazakhstan Tenge", "symbol": "лв" } },
    { "LAK": { "name": "Laos Kip", "symbol": "₭" } },
    { "LBP": { "name": "Lebanon Pound", "symbol": "£" } },
    { "LKR": { "name": "Sri Lanka Rupee", "symbol": "₨" } },
    { "LRD": { "name": "Liberia Dollar", "symbol": "$" } },
    { "LSL": { "name": "Lesotho Loti", "symbol": "L" } },
    { "LYD": { "name": "Libya Dinar", "symbol": "ل.د" } },
    { "MAD": { "name": "Morocco Dirham", "symbol": "د.م." } },
    { "MDL": { "name": "Moldova Leu", "symbol": "lei" } },
    { "MGA": { "name": "Madagascar Ariary", "symbol": "Ar" } },
    { "MKD": { "name": "Macedonia Denar", "symbol": "ден" } },
    { "MMK": { "name": "Myanmar Kyat", "symbol": "K" } },
    { "MNT": { "name": "Mongolia Tughrik", "symbol": "₮" } },
    { "MOP": { "name": "Macau Pataca", "symbol": "MOP$" } },
    { "MRU": { "name": "Mauritania Ouguiya", "symbol": "UM" } },
    { "MUR": { "name": "Mauritius Rupee", "symbol": "₨" } },
    { "MVR": { "name": "Maldives Rufiyaa", "symbol": "Rf" } },
    { "MWK": { "name": "Malawi Kwacha", "symbol": "MK" } },
    { "MXN": { "name": "Mexico Peso", "symbol": "$" } },
    { "MYR": { "name": "Malaysia Ringgit", "symbol": "RM" } },
    { "MZN": { "name": "Mozambique Metical", "symbol": "MT" } },
    { "NAD": { "name": "Namibia Dollar", "symbol": "$" } },
    { "NGN": { "name": "Nigeria Naira", "symbol": "₦" } },
    { "NIO": { "name": "Nicaragua Cordoba", "symbol": "C$" } },
    { "NOK": { "name": "Norway Krone", "symbol": "kr" } },
    { "NPR": { "name": "Nepal Rupee", "symbol": "₨" } },
    { "NZD": { "name": "New Zealand Dollar", "symbol": "$" } },
    { "OMR": { "name": "Oman Rial", "symbol": "﷼" } },
    { "PAB": { "name": "Panama Balboa", "symbol": "B/." } },
    { "PEN": { "name": "Peru Sol", "symbol": "S/." } },
    { "PGK": { "name": "Papua New Guinea Kina", "symbol": "K" } },
    { "PHP": { "name": "Philippines Peso", "symbol": "₱" } },
    { "PKR": { "name": "Pakistan Rupee", "symbol": "₨" } },
    { "PLN": { "name": "Poland Zloty", "symbol": "zł" } },
    { "PYG": { "name": "Paraguay Guarani", "symbol": "Gs" } },
    { "QAR": { "name": "Qatar Riyal", "symbol": "﷼" } },
    { "RON": { "name": "Romania Leu", "symbol": "lei" } },
    { "RSD": { "name": "Serbia Dinar", "symbol": "Дин." } },
    { "RUB": { "name": "Russia Ruble", "symbol": "₽" } },
    { "RWF": { "name": "Rwanda Franc", "symbol": "RF" } },
    { "SAR": { "name": "Saudi Arabia Riyal", "symbol": "﷼" } },
    { "SBD": { "name": "Solomon Islands Dollar", "symbol": "$" } },
    { "SCR": { "name": "Seychelles Rupee", "symbol": "₨" } },
    { "SDG": { "name": "Sudan Pound", "symbol": "£" } },
    { "SEK": { "name": "Sweden Krona", "symbol": "kr" } },
    { "SGD": { "name": "Singapore Dollar", "symbol": "$" } },
    { "SHP": { "name": "Saint Helena Pound", "symbol": "£" } },
    { "SLL": { "name": "Sierra Leone Leone", "symbol": "Le" } },
    { "SOS": { "name": "Somalia Shilling", "symbol": "S" } },
    { "SRD": { "name": "Suriname Dollar", "symbol": "$" } },
    { "SSP": { "name": "South Sudanese Pound", "symbol": "£" } },
    { "STN": { "name": "São Tomé and Príncipe Dobra", "symbol": "Db" } },
    { "SYP": { "name": "Syria Pound", "symbol": "£" } },
    { "SZL": { "name": "Swaziland Lilangeni", "symbol": "E" } },
    { "THB": { "name": "Thailand Baht", "symbol": "฿" } },
    { "TJS": { "name": "Tajikistan Somoni", "symbol": "ЅМ" } },
    { "TMT": { "name": "Turkmenistan Manat", "symbol": "T" } },
    { "TND": { "name": "Tunisia Dinar", "symbol": "د.ت" } },
    { "TOP": { "name": "Tonga Pa'anga", "symbol": "T$" } },
    { "TRY": { "name": "Turkey Lira", "symbol": "₺" } },
    { "TTD": { "name": "Trinidad and Tobago Dollar", "symbol": "TT$" } },
    { "TVD": { "name": "Tuvalu Dollar", "symbol": "$" } },
    { "TWD": { "name": "Taiwan New Dollar", "symbol": "NT$" } },
    { "TZS": { "name": "Tanzania Shilling", "symbol": "TSh" } },
    { "UAH": { "name": "Ukraine Hryvnia", "symbol": "₴" } },
    { "UGX": { "name": "Uganda Shilling", "symbol": "USh" } },
    { "USD": { "name": "United States Dollar", "symbol": "$" } },
    { "UYU": { "name": "Uruguay Peso", "symbol": "$U" } },
    { "UZS": { "name": "Uzbekistan Som", "symbol": "лв" } },
    { "VES": { "name": "Venezuela Bolívar", "symbol": "Bs" } },
    { "VND": { "name": "Viet Nam Dong", "symbol": "₫" } },
    { "VUV": { "name": "Vanuatu Vatu", "symbol": "VT" } },
    { "WST": { "name": "Samoa Tala", "symbol": "WS$" } },
    { "XAF": { "name": "Communauté Financière Africaine (BEAC) CFA Franc BEAC", "symbol": "FCFA" } },
    { "XCD": { "name": "East Caribbean Dollar", "symbol": "$" } },
    { "XDR": { "name": "International Monetary Fund (IMF) Special Drawing Rights", "symbol": "SDR" } },
    { "XOF": { "name": "Communauté Financière Africaine (BCEAO) Franc", "symbol": "CFA" } },
    { "XPF": { "name": "Comptoirs Français du Pacifique (CFP) Franc", "symbol": "CFPF" } },
    { "YER": { "name": "Yemen Rial", "symbol": "﷼" } },
    { "ZAR": { "name": "South Africa Rand", "symbol": "R" } },
    { "ZMW": { "name": "Zambia Kwacha", "symbol": "ZK" } },
    { "ZWL": { "name": "Zimbabwe Dollar", "symbol": "Z$" } }
]